# Generated by Django 2.1.3 on 2018-11-11 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('M', 'Female')], default='M', max_length=1)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Guest', 'Guest')], default='Guest', max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
